package ro.siit.tema2;

/**
 * This is a SalesRepresentative; each rep has a number of sales, a revenue and a quota / sale.
 * Sales guy 1 has 10 sales with a quota of 500$. He has achieved 5000$ worth of sales.
 * Sales guy 2 has 7 sales with a quota of 800$. He has achieved 5600$ worth of sales.
 */
public class SalesRepresentative {
    private int sales;
    private int revenue;
    private int quota;

    /**
     * Creates a SalesRepresentative.
     *
     * @param sales   the number of sales made by a sales rep.
     * @param revenue the amount of revenue generated by a sales rep.
     * @param quota   the quota from the revenue generated by a sales rep.
     */
    public SalesRepresentative(int sales, int revenue, int quota) {
        this.sales = sales;
        this.revenue = revenue;
        this.quota = quota;
    }

    /**
     * Gets the number of sales made by a sales rep.
     *
     * @return the number of sales made by a sales rep.
     */
    public int getSales() {
        return sales;
    }

    /**
     * Gets the amount of revenue generated by a sales rep.
     *
     * @return the amount of revenue generated by a sales rep.
     */
    public int getRevenue() {
        return revenue;
    }

    /**
     * Gets the quota from the revenue generated by a sales rep.
     *
     * @return the quota from the revenue generated by a sales rep.
     */
    public int getQuota() {
        return quota;
    }

    /**
     * Transforms Sales Representative into a string including the sales, revenue and quota.
     *
     * @return the string representation.
     */
    @Override
    public String toString() {
        return "SalesRepresentative{" +
                "sales=" + sales +
                ", revenue=" + revenue +
                ", quota=" + quota +
                '}';
    }
}
